name: C Project Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile
        run: |
          make

      - name: Run Tests
        run: |
          make run
