name: C Project Release

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile
        run: |
          cd src
          make all

      - name: Run Tests
        run: |
          cd test
          make test

      - name: Create Release Directory
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir release
          cp out/libcmap.* release/

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/libcmap.*
          asset_name: libcmap
          asset_content_type: application/octet-stream
